'use strict';
const $=id=>document.getElementById(id);
let items=[],selected=null,inputFile=null,task='image',jobId=null,pollTimer=null,toastTimer=null;
const viewer=$('main-viewer');
const number=n=>n==null?'Unverified':new Intl.NumberFormat().format(n);
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500)}
async function api(url,options){const response=await fetch(url,options);if(!response.ok){let data;try{data=await response.json()}catch{data={detail:response.statusText}}throw new Error(typeof data.detail==='string'?data.detail:'Please check the selected settings.')}return response.json()}
function setView(name){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===name));document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===name));if(name==='library')refreshLibrary().catch(e=>toast(e.message))}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>setView(el.dataset.view)));
function setTask(value){task=value;document.querySelectorAll('[data-task]').forEach(el=>el.classList.toggle('active',el.dataset.task===value));$('file').accept=value==='image'?'image/png,image/jpeg,image/webp':'.glb,.obj,.stl,.ply';$('upload-title').textContent=value==='image'?'Drop your image here':'Drop your mesh here';$('upload-hint').textContent=value==='image'?'or click to browse · PNG, JPG, WEBP':'or click to browse · GLB, OBJ, STL, PLY';['use-example','texture-toggle','texture-resolution-field'].forEach(id=>$(id).hidden=value!=='image');clearInput()}
document.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('click',()=>setTask(el.dataset.task)));
function clearInput(){inputFile=null;$('file').value='';$('input-preview').hidden=true;$('input-preview').removeAttribute('src');$('file-tag').hidden=true;$('upload-copy').hidden=false}
function chooseFile(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();const allowed=task==='image'?['png','jpg','jpeg','webp']:['glb','obj','stl','ply'];if(!allowed.includes(ext))return toast('Choose a supported '+(task==='image'?'image':'mesh')+' file.');const max=task==='image'?30:512;if(file.size>max*1024*1024)return toast(`Maximum input size is ${max} MB.`);inputFile=file;$('file-tag').textContent=file.name;$('file-tag').hidden=false;if(task==='image'){const url=URL.createObjectURL(file);$('input-preview').onload=()=>URL.revokeObjectURL(url);$('input-preview').src=url;$('input-preview').hidden=false;$('upload-copy').hidden=true}else{$('upload-title').textContent=file.name}if(!$('name').value)$('name').value=file.name.replace(/\.[^.]+$/,'').replaceAll('_',' ')}
$('file').addEventListener('change',e=>chooseFile(e.target.files[0]));
$('dropzone').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('file').click()}});
['dragenter','dragover'].forEach(type=>$('dropzone').addEventListener(type,e=>{e.preventDefault();$('dropzone').classList.add('dragover')}));
['dragleave','drop'].forEach(type=>$('dropzone').addEventListener(type,e=>{e.preventDefault();$('dropzone').classList.remove('dragover');if(type==='drop')chooseFile(e.dataTransfer.files[0])}));
$('use-example').addEventListener('click',async()=>{try{const response=await fetch('/api/assets/example-axe/source.png');if(!response.ok)throw new Error('Example image is unavailable.');chooseFile(new File([await response.blob()],'wolf-rune-axe.png',{type:'image/png'}));$('name').value='Wolf rune axe';toast('Example loaded. Ready to generate.')}catch(e){toast(e.message)}});
$('texture').addEventListener('change',()=>{$('texture-size').disabled=!$('texture').checked});
function showVariant(file){if(!selected)return;const version=selected.versions.find(v=>v.file===file)||selected.versions[0];if(!version)return;viewer.src=version.url;viewer.alt='Interactive 3D model of '+selected.name;$('variant').value=version.file;$('download-model').href=version.url+'?download=true';$('result-summary').textContent=version.faces?number(version.faces)+' triangles':'Triangle count unavailable';$('topology').textContent=version.watertight===true?'Watertight check passed':version.watertight===false?'Topology warning · not watertight':'Topology not verified';$('topology').style.color=version.watertight===false?'#efb265':'';$('result-badge').textContent=selected.example?'INCLUDED EXAMPLE':file==='final.glb'?'GEOMETRY ONLY':'TEXTURED ASSET'}
function openCreation(item,switchView=true){selected=item;$('result-name').textContent=item.name;$('variant').replaceChildren(...item.versions.map(v=>{const el=document.createElement('option');el.value=v.file;el.textContent=v.label;return el}));$('downloads').replaceChildren(...item.files.map(f=>{const a=document.createElement('a');a.href=f.url+'?download=true';a.textContent=f.name+' ↓';return a}));showVariant(item.versions[0]?.file);if(switchView){setView('studio');$('result-name').scrollIntoView({behavior:'smooth',block:'start'})}}
$('variant').addEventListener('change',()=>showVariant($('variant').value));
function renderCards(){const cards=items.map(item=>{const button=document.createElement('button');button.className='card';button.type='button';button.setAttribute('aria-label','Open '+item.name);const imageBox=document.createElement('div');imageBox.className='card-image';const image=document.createElement('img');image.src=item.thumbnail;image.alt=item.name;image.loading='lazy';imageBox.append(image);const tag=document.createElement('span');tag.textContent=item.example?'INCLUDED EXAMPLE':item.versions.some(v=>v.file==='textured.glb')?'TEXTURED':'GEOMETRY';imageBox.append(tag);const body=document.createElement('div');body.className='card-body';const title=document.createElement('strong');title.textContent=item.name;const detail=document.createElement('p');const first=item.versions[0];detail.textContent=(first?.faces?number(first.faces)+' triangles':'Saved creation')+'  ·  Explore ↗';body.append(title,detail);button.append(imageBox,body);button.addEventListener('click',()=>openCreation(item));return button});$('cards').replaceChildren(...cards);$('library-count').textContent=items.filter(i=>!i.example).length}
async function refreshLibrary(){items=await api('/api/library');renderCards();return items}
$('refresh').addEventListener('click',()=>refreshLibrary().then(()=>toast('Library refreshed.')).catch(e=>toast(e.message)));
$('rotate').addEventListener('click',()=>{viewer.autoRotate=!viewer.autoRotate;$('rotate').classList.toggle('active',viewer.autoRotate)});
$('reset-camera').addEventListener('click',()=>{viewer.cameraOrbit='35deg 75deg auto';viewer.cameraTarget='auto auto auto';viewer.fieldOfView='auto';viewer.jumpCameraToGoal()});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await viewer.parentElement.requestFullscreen()}catch{toast('Fullscreen is unavailable in this browser.')}});
viewer.addEventListener('error',()=>toast('The 3D preview could not load. The model is still available to download.'));
function running(value){$('generate').disabled=value;$('stop').hidden=!value;$('progress').hidden=!value}
function stage(log){if(log.includes('[BakeNode]'))return 'Baking material maps';if(log.includes('UV')||log.includes('rasteriz'))return 'Projecting textures';if(log.includes('FastDecimator'))return 'Refining the mesh';if(log.includes('WTiVo'))return 'Closing the surface';if(log.includes('Generation complete'))return 'Reconstructing geometry';if(log.includes('Loading'))return 'Generating geometry and materials';return 'Preparing your creation'}
async function poll(){if(!jobId)return;try{const job=await api('/api/jobs/'+jobId);$('log').textContent=job.log;$('elapsed').textContent=Math.floor(job.elapsed/60)+'m '+job.elapsed%60+'s';$('status-title').textContent=job.state==='running'?(job.message.startsWith('Rendering')?'Rendering library preview':stage(job.log)):job.state==='complete'?'Your creation is ready.':job.state==='cancelled'?'Generation stopped.':'This run needs attention.';$('status-message').textContent=job.message;if(job.state!=='running'){running(false);clearTimeout(pollTimer);jobId=null;await refreshLibrary();const item=items.find(i=>i.id===job.id);if(item)openCreation(item,false);toast(job.message);return}pollTimer=setTimeout(poll,1800)}catch(e){$('status-message').textContent='Connection interrupted. Reconnecting…';pollTimer=setTimeout(poll,4000)}}
$('create-form').addEventListener('submit',async e=>{e.preventDefault();if(!inputFile)return toast('Choose an input file first.');if(jobId)return toast('A generation is already running.');const form=new FormData();form.append('file',inputFile);form.append('name',$('name').value||'Untitled creation');form.append('task',task);for(const [key,id] of [['resolution','resolution'],['texture_size','texture-size'],['seed','seed'],['faces','faces']])form.append(key,$(id).value);form.append('texture',String($('texture').checked));form.append('quad',String($('quad').checked));running(true);$('status-title').textContent='Uploading your starting point…';$('status-message').textContent='Your input stays on this machine.';try{const result=await api('/api/jobs',{method:'POST',body:form});jobId=result.id;poll()}catch(error){running(false);$('status-title').textContent='Could not start this run.';$('status-message').textContent=error.message;toast(error.message)}});
$('stop').addEventListener('click',async()=>{if(!jobId)return;try{await api('/api/jobs/'+jobId+'/stop',{method:'POST'});$('status-message').textContent='Stopping worker processes…'}catch(e){toast(e.message)}});
async function init(){try{await refreshLibrary();const example=items.find(i=>i.example);if(example)openCreation(example,false);const current=await api('/api/jobs/current');if(current){jobId=current.id;running(true);poll()}}catch(e){toast('Could not load the studio: '+e.message)}try{const system=await api('/api/system');$('gpu-label').textContent=system.gpu;if(!system.available)$('status-message').textContent='An NVIDIA GPU and compatible driver are required for generation. You can still explore saved models.'}catch{$('gpu-label').textContent='GPU information unavailable'}}
init();
